// Types cho YouTube Realtime Translator Extension

// Language definitions
export const LANGUAGE_CODES = {
  auto: "Tự động phát hiện",
  vi: "Tiếng Việt",
  en: "English",
  ja: "日本語",
  ko: "한국어",
  zh: "中文",
  th: "ไทย",
  fr: "Français",
  de: "Deutsch",
  es: "Español",
  ru: "Русский",
  ar: "العربية",
  hi: "हिन्दी",
  it: "Italiano",
  pt: "Português",
  nl: "Nederlands",
  sv: "Svenska",
  da: "Dansk",
  no: "Norsk",
  fi: "Suomi",
  pl: "Polski",
  tr: "Türkçe",
  he: "עברית",
  id: "Bahasa Indonesia",
  ms: "Bahasa Melayu"
} as const

export type LanguageCode = keyof typeof LANGUAGE_CODES

export interface SubtitleEntry {
  id: string
  start: number // thời gian bắt đầu (giây)
  end: number // thời gian kết thúc (giây)
  text: string // nội dung subtitle gốc
  translatedText?: string // nội dung đã dịch
}

export interface VideoInfo {
  videoId: string
  title: string
  duration: number
  hasSubtitles: boolean
  availableLanguages: string[]
}

export interface TranslationSettings {
  sourceLanguage: LanguageCode
  targetLanguage: LanguageCode
  autoDetect: boolean
  enableTTS: boolean
  ttsSpeed: number
  ttsVoice: string
}

export interface YouTubeCaption {
  languageCode: string
  name: string
  url: string
  isAutoGenerated: boolean
}

export interface TranslatorState {
  isActive: boolean
  isLoading: boolean
  currentVideo: VideoInfo | null
  settings: TranslationSettings
  subtitles: SubtitleEntry[]
  currentSubtitleIndex: number
}

export interface TTSOptions {
  text: string
  language: string
  rate: number
  pitch: number
  volume: number
  ttsVoice?: string
}

export interface StorageData {
  settings: TranslationSettings
  recentLanguages: string[]
  isEnabled: boolean
}

// Events
export interface ExtensionMessage {
  type:
    | "TRANSLATE_SUBTITLE"
    | "UPDATE_SETTINGS"
    | "GET_VIDEO_INFO"
    | "TOGGLE_TRANSLATOR"
  payload?: any
}

export interface SubtitleUpdateEvent {
  type: "SUBTITLE_UPDATE"
  subtitle: SubtitleEntry
  videoTime: number
}
